import { DecisionCard, ExperienceState, RegionSnapshot } from './types';

export const regions: RegionSnapshot[] = [
  {
    id: 'north-crown',
    name: 'North Crown',
    capital: 'Halcyon Bay',
    moodLabel: 'Proud, storm-tested, watchful',
    culturalNote: 'Shipyards, fisheries, and practical kindness sit side by side here.',
    clubAnchor: 'North Crown Mariners',
    currentPressure: 'Coastal flood readiness and youth opportunity',
    whatPeopleCareAbout: 'Security that protects daily life, not just headlines.',
    coastline: 'Northern Atlantic shield coast',
    metrics: { trust: 66, wellbeing: 58, pressure: 54 },
  },
  {
    id: 'eastbridge',
    name: 'Eastbridge',
    capital: 'Port Aurelia',
    moodLabel: 'Ambitious, crowded, inventive',
    culturalNote: 'Rail corridors, tech firms, and mixed-income neighborhoods pull in different directions.',
    clubAnchor: 'Eastbridge Union',
    currentPressure: 'Housing strain and commuter stress',
    whatPeopleCareAbout: 'Whether growth still feels fair.',
    coastline: 'Estuary and metro bay',
    metrics: { trust: 59, wellbeing: 55, pressure: 70 },
  },
  {
    id: 'greenfold',
    name: 'Greenfold',
    capital: 'Larksmead',
    moodLabel: 'Calm, local, future-minded',
    culturalNote: 'Farms, river towns, and clean-energy pride shape the local voice.',
    clubAnchor: 'Greenfold Vale',
    currentPressure: 'Energy transition and resilience investment',
    whatPeopleCareAbout: 'Leaving the land in better shape than it was found.',
    coastline: 'Western wetlands and river delta',
    metrics: { trust: 71, wellbeing: 64, pressure: 46 },
  },
  {
    id: 'southwatch',
    name: 'Southwatch',
    capital: 'Sable Point',
    moodLabel: 'Restless, young, community-minded',
    culturalNote: 'Dense estates, music scenes, and sport-heavy identity make belonging a live issue.',
    clubAnchor: 'Southwatch City',
    currentPressure: 'School meals, buses, and youth boredom',
    whatPeopleCareAbout: 'Whether leaders notice everyday strain before it turns into anger.',
    coastline: 'Southern urban shoreline',
    metrics: { trust: 52, wellbeing: 49, pressure: 74 },
  },
  {
    id: 'frostmere',
    name: 'Frostmere',
    capital: 'Winterhaven',
    moodLabel: 'Remote, resilient, under-served',
    culturalNote: 'Mountain routes and long winters make service access feel personal.',
    clubAnchor: 'Frostmere Athletic',
    currentPressure: 'Remote health access and transport reliability',
    whatPeopleCareAbout: 'Not being treated as too far away to matter.',
    coastline: 'Northern fjord and highland edge',
    metrics: { trust: 61, wellbeing: 53, pressure: 67 },
  },
  {
    id: 'riverglass',
    name: 'Riverglass',
    capital: 'Leograd',
    moodLabel: 'Civic, reflective, politically alert',
    culturalNote: 'The capital region believes in institutions, but it expects them to work.',
    clubAnchor: 'Riverglass Sporting',
    currentPressure: 'Hospital queues and cost-of-living pressure',
    whatPeopleCareAbout: 'Whether public trust is matched by public competence.',
    coastline: 'Central river basin and civic coast',
    metrics: { trust: 64, wellbeing: 57, pressure: 62 },
  },
];

export const decisions: DecisionCard[] = [
  {
    id: 'school-meals',
    title: 'School Meals and Calm Afternoons',
    theme: 'Child wellbeing',
    situation: 'Southwatch schools and Riverglass family centers are warning that hungry afternoons are turning into missed learning, shame, and sharper behavior problems.',
    whyItMatters: 'A society that lets children carry adult stress alone pays for it later in trust, safety, and hope.',
    regionIds: ['southwatch', 'riverglass', 'north-crown'],
    options: [
      {
        id: 'universal',
        label: 'Fund universal meals and after-school calm spaces',
        summary: 'A generous response that costs money but lowers daily strain where it matters most.',
        humaneLogic: 'Treat food, calm, and dignity as infrastructure for a decent society.',
        metricEffects: { happiness: 4, health: 3, fairness: 5, trust: 4, prosperity: -2, stress: -5 },
        regionEffects: [
          { regionId: 'southwatch', wellbeing: 7, pressure: -8, trust: 5 },
          { regionId: 'riverglass', wellbeing: 5, pressure: -4 },
        ],
        reflection: 'Children feel the state as care, not lecture. Some budget hawks complain, but the country feels kinder and steadier.',
      },
      {
        id: 'pilot',
        label: 'Pilot meals only in the highest-stress districts',
        summary: 'Cheaper and still helpful, but some communities feel left behind.',
        humaneLogic: 'Target support carefully, but risk turning fairness into a postcode argument.',
        metricEffects: { health: 2, fairness: 1, trust: 1, prosperity: 1, stress: -2 },
        regionEffects: [
          { regionId: 'southwatch', wellbeing: 5, pressure: -5 },
          { regionId: 'eastbridge', trust: -2, pressure: 2 },
        ],
        reflection: 'The help works where it lands, but some families ask why decency must be rationed.',
      },
      {
        id: 'charity',
        label: 'Leave it to councils and charities',
        summary: 'The budget stays calmer, but insecurity deepens in the places already carrying too much.',
        humaneLogic: 'This keeps central government tidy while letting strain spread socially.',
        metricEffects: { trust: -4, fairness: -5, prosperity: 2, stress: 4, fragility: 3 },
        regionEffects: [
          { regionId: 'southwatch', wellbeing: -6, pressure: 7, trust: -5 },
          { regionId: 'riverglass', wellbeing: -3, pressure: 4 },
        ],
        reflection: 'You saved money today, but the country learns that care depends on luck and postcode.',
      },
    ],
  },
  {
    id: 'flood-readiness',
    title: 'Stormbelt Readiness',
    theme: 'Climate resilience',
    situation: 'North Crown and Greenfold both want stronger flood defenses, evacuation plans, and resilient local power, but the works are expensive and unglamorous.',
    whyItMatters: 'Preparedness rarely wins applause on the day it is funded. It matters when weather stops being polite.',
    regionIds: ['north-crown', 'greenfold', 'frostmere'],
    options: [
      {
        id: 'resilience-first',
        label: 'Fund local resilience and protect vulnerable streets now',
        summary: 'A patient, grounded investment in safety and resilience.',
        humaneLogic: 'Prevent harm before disaster headlines force your hand.',
        metricEffects: { safety: 6, resilience: 7, trust: 3, prosperity: -2, stress: -3 },
        regionEffects: [
          { regionId: 'north-crown', wellbeing: 5, pressure: -6, trust: 4 },
          { regionId: 'greenfold', wellbeing: 3, pressure: -4 },
        ],
        reflection: 'Nothing flashy happens today. That is the point. Homes and routes feel more secure, and people notice the seriousness.',
      },
      {
        id: 'insurance-relief',
        label: 'Offer partial relief and postpone the bigger works',
        summary: 'This helps with recovery costs but leaves exposure in place.',
        humaneLogic: 'Soften pain now, but leave the next storm to arrive on old terms.',
        metricEffects: { safety: 1, trust: -1, resilience: -2, prosperity: 1, stress: 1 },
        regionEffects: [
          { regionId: 'north-crown', pressure: 2 },
          { regionId: 'greenfold', trust: -2, pressure: 3 },
        ],
        reflection: 'People are grateful for the relief, but they can tell you dodged the harder duty.',
      },
    ],
  },
  {
    id: 'housing-belonging',
    title: 'Homes, Belonging, and the Last Bus Home',
    theme: 'Housing and transport',
    situation: 'Eastbridge is growing fast while Southwatch families are getting squeezed. New homes, better buses, and calmer planning rules could ease the strain, but wealthy blocs are loud.',
    whyItMatters: 'A country that cannot house people without exhausting them turns growth into resentment.',
    regionIds: ['eastbridge', 'southwatch', 'riverglass'],
    options: [
      {
        id: 'build-and-bus',
        label: 'Build mixed housing near transit and protect bus routes',
        summary: 'A balanced answer that helps affordability and daily dignity, even if it causes local arguments.',
        humaneLogic: 'Growth should feel livable, not extractive.',
        metricEffects: { fairness: 4, prosperity: 3, trust: 3, resilience: 2, stress: -4 },
        regionEffects: [
          { regionId: 'eastbridge', pressure: -6, trust: 3 },
          { regionId: 'southwatch', wellbeing: 4, pressure: -3 },
        ],
        reflection: 'The debate is noisy, but commuting gets easier and the housing story starts to feel less hopeless.',
      },
      {
        id: 'let-market-rip',
        label: 'Leave housing and transport mostly to the market',
        summary: 'This flatters short-term investors, but everyday life gets sharper and meaner.',
        humaneLogic: 'It treats a social system like a price chart.',
        metricEffects: { prosperity: 2, trust: -4, fairness: -4, stress: 5, fragility: 3 },
        regionEffects: [
          { regionId: 'eastbridge', pressure: 6, trust: -4 },
          { regionId: 'southwatch', wellbeing: -4, pressure: 5 },
        ],
        reflection: 'The numbers look tidy for a moment, but people feel the country drifting toward a winner-takes-more bargain.',
      },
    ],
  },
];

export const initialState: ExperienceState = {
  metrics: {
    happiness: 63,
    health: 61,
    safety: 67,
    fairness: 58,
    prosperity: 60,
    trust: 62,
    resilience: 59,
    stress: 44,
    fragility: 37,
  },
  regions,
  currentDecisionIndex: 0,
  selectedRegionId: 'riverglass',
  history: [],
};
