import { CountryState, InstitutionState, IssueTrack, RegionState, WorldState } from './types';

export const seasons = ['Late Winter', 'Early Spring', 'High Spring', 'Harvest Light', 'Storm Season'];

export const initialCountryState: CountryState = {
  turn: 1,
  season: seasons[0],
  headlineSituation: 'Leoland feels basically hopeful, but daily strain is rising faster than trust can comfortably absorb.',
  metrics: {
    happiness: 63,
    health: 61,
    safety: 67,
    fairness: 58,
    prosperity: 60,
    trust: 62,
    resilience: 59,
    stress: 44,
    fragility: 37,
  },
  treasury: 56,
  activeScenarioId: null,
  activeScenarioIds: [],
  completedScenarioIds: [],
  history: [],
  pulse: {
    summary: 'Leoland still feels hopeful, but the country is asking for steadier care in daily life.',
    emotionalWeather: 'Hopeful with gathering strain',
    nationalStory: 'People still believe the country can be governed well, but they want that belief to feel practical.',
    bestImproving: 'Community life is still helping hold places together.',
    mostFragile: 'Housing pressure and service strain are quietly pulling belonging apart.',
    institutionSpotlightId: 'community_life',
    institutionSpotlightSummary: 'Community life is still one of the places where warmth and belonging can grow faster than cynicism.',
    culturalMoment: {
      title: 'A season of local gatherings',
      summary: 'School halls, clubhouses, and town squares still give people places to feel part of the country together.',
      tone: 'hope',
      regionId: 'riverglass',
    },
  },
};

export const initialRegions: RegionState[] = [
  {
    id: 'north-crown',
    name: 'North Crown',
    identity: {
      capital: 'Halcyon Bay',
      moodLabel: 'Proud, storm-tested, watchful',
      culturalNote: 'Shipyards, fisheries, and practical kindness sit side by side here.',
      clubAnchor: 'North Crown Mariners',
      whatPeopleCareAbout: 'Security that protects daily life, not just headlines.',
      coastline: 'Northern Atlantic shield coast',
    },
    mood: 64,
    trust: 66,
    wellbeing: 58,
    pressure: 54,
    serviceStrain: 45,
    belonging: 68,
    resilience: 71,
    civicPride: 72,
    youthOutlook: 59,
    communityWarmth: 66,
    neglectFeeling: 29,
    currentKeyIssue: 'Flood readiness and youth opportunity',
    headline: 'People want seriousness before the next bad storm arrives.',
    notes: 'Calm competence is respected more than spectacle here.',
  },
  {
    id: 'eastbridge',
    name: 'Eastbridge',
    identity: {
      capital: 'Port Aurelia',
      moodLabel: 'Ambitious, crowded, inventive',
      culturalNote: 'Rail corridors, tech firms, and mixed-income neighbourhoods pull in different directions.',
      clubAnchor: 'Eastbridge Union',
      whatPeopleCareAbout: 'Whether growth still feels fair.',
      coastline: 'Estuary and metro bay',
    },
    mood: 57,
    trust: 59,
    wellbeing: 55,
    pressure: 70,
    serviceStrain: 63,
    belonging: 52,
    resilience: 54,
    civicPride: 58,
    youthOutlook: 48,
    communityWarmth: 51,
    neglectFeeling: 58,
    currentKeyIssue: 'Housing strain and commuter stress',
    headline: 'People are tired of being told that pressure is just the price of success.',
    notes: 'Prosperity without belonging is wearing thin.',
  },
  {
    id: 'greenfold',
    name: 'Greenfold',
    identity: {
      capital: 'Larksmead',
      moodLabel: 'Calm, local, future-minded',
      culturalNote: 'Farms, river towns, and clean-energy pride shape the local voice.',
      clubAnchor: 'Greenfold Vale',
      whatPeopleCareAbout: 'Leaving the land in better shape than it was found.',
      coastline: 'Western wetlands and river delta',
    },
    mood: 69,
    trust: 71,
    wellbeing: 64,
    pressure: 46,
    serviceStrain: 39,
    belonging: 67,
    resilience: 63,
    civicPride: 74,
    youthOutlook: 64,
    communityWarmth: 69,
    neglectFeeling: 24,
    currentKeyIssue: 'Energy transition and flood resilience',
    headline: 'People support change when it still feels rooted and fair.',
    notes: 'The region likes ambition that stays practical.',
  },
  {
    id: 'southwatch',
    name: 'Southwatch',
    identity: {
      capital: 'Sable Point',
      moodLabel: 'Restless, young, community-minded',
      culturalNote: 'Dense estates, music scenes, and sport-heavy identity make belonging a live issue.',
      clubAnchor: 'Southwatch City',
      whatPeopleCareAbout: 'Whether leaders notice everyday strain before it turns into anger.',
      coastline: 'Southern urban shoreline',
    },
    mood: 48,
    trust: 52,
    wellbeing: 49,
    pressure: 74,
    serviceStrain: 71,
    belonging: 46,
    resilience: 43,
    civicPride: 55,
    youthOutlook: 41,
    communityWarmth: 52,
    neglectFeeling: 67,
    currentKeyIssue: 'School meals, buses, and youth belonging',
    headline: 'Families are resilient, but they are tired of carrying too much alone.',
    notes: 'Visible care matters quickly here.',
  },
  {
    id: 'frostmere',
    name: 'Frostmere',
    identity: {
      capital: 'Winterhaven',
      moodLabel: 'Remote, resilient, under-served',
      culturalNote: 'Mountain routes and long winters make service access feel personal.',
      clubAnchor: 'Frostmere Athletic',
      whatPeopleCareAbout: 'Not being treated as too far away to matter.',
      coastline: 'Northern fjord and highland edge',
    },
    mood: 56,
    trust: 61,
    wellbeing: 53,
    pressure: 67,
    serviceStrain: 66,
    belonging: 58,
    resilience: 57,
    civicPride: 61,
    youthOutlook: 50,
    communityWarmth: 56,
    neglectFeeling: 55,
    currentKeyIssue: 'Rural health access and transport reliability',
    headline: 'Distance feels political when services thin out.',
    notes: 'Respect here means presence, not promises.',
  },
  {
    id: 'riverglass',
    name: 'Riverglass',
    identity: {
      capital: 'Leograd',
      moodLabel: 'Civic, reflective, politically alert',
      culturalNote: 'The capital region believes in institutions, but it expects them to work.',
      clubAnchor: 'Riverglass Sporting',
      whatPeopleCareAbout: 'Whether public trust is matched by public competence.',
      coastline: 'Central river basin and civic coast',
    },
    mood: 60,
    trust: 64,
    wellbeing: 57,
    pressure: 62,
    serviceStrain: 58,
    belonging: 55,
    resilience: 56,
    civicPride: 63,
    youthOutlook: 53,
    communityWarmth: 58,
    neglectFeeling: 47,
    currentKeyIssue: 'Hospital queues and cost-of-living pressure',
    headline: 'People still believe in public life, but patience is not infinite.',
    notes: 'Competence is noticed more than branding.',
  },
];

export const initialInstitutions: InstitutionState[] = [
  { id: 'schools', name: 'Schools', strength: 63, strain: 59, publicTrust: 64, fairnessImpact: 68, effectiveness: 60, morale: 58, heldness: 66, note: 'Teachers are carrying hunger and anxiety as well as learning.' },
  { id: 'healthcare', name: 'Healthcare', strength: 61, strain: 69, publicTrust: 66, fairnessImpact: 71, effectiveness: 56, morale: 52, heldness: 64, note: 'Queues are stretching, especially far from the capital.' },
  { id: 'housing', name: 'Housing', strength: 52, strain: 74, publicTrust: 49, fairnessImpact: 73, effectiveness: 48, morale: 43, heldness: 46, note: 'Pressure is eroding belonging in growth regions.' },
  { id: 'transport', name: 'Transport', strength: 56, strain: 64, publicTrust: 54, fairnessImpact: 63, effectiveness: 53, morale: 49, heldness: 52, note: 'Reliability feels uneven between the capital and the edges.' },
  { id: 'local_services', name: 'Local services', strength: 58, strain: 62, publicTrust: 57, fairnessImpact: 67, effectiveness: 55, morale: 53, heldness: 60, note: 'Libraries, youth centres, and advice services are stretched.' },
  { id: 'emergency_resilience', name: 'Emergency resilience', strength: 60, strain: 55, publicTrust: 61, fairnessImpact: 58, effectiveness: 62, morale: 59, heldness: 57, note: 'Preparedness is decent, but climate shocks are getting sharper.' },
  { id: 'community_life', name: 'Community life', strength: 62, strain: 48, publicTrust: 65, fairnessImpact: 61, effectiveness: 67, morale: 69, heldness: 71, note: 'Festivals, clubs, and civic pride still help glue places together.' },
  { id: 'civic_information', name: 'Civic information', strength: 54, strain: 57, publicTrust: 52, fairnessImpact: 55, effectiveness: 51, morale: 47, heldness: 49, note: 'People want honesty and clarity more than spin.' },
];

export const initialIssues: IssueTrack[] = [
  { id: 'housing_strain', name: 'Housing strain', pressure: 74, trend: 'worsening', headline: 'Homes are too scarce near work and transport.' },
  { id: 'hospital_queues', name: 'Hospital queues', pressure: 68, trend: 'worsening', headline: 'Care is still trusted, but access is slowing.' },
  { id: 'flooding_risk', name: 'Flooding risk', pressure: 56, trend: 'steady', headline: 'Storms are testing whether preparedness is real or rhetorical.' },
  { id: 'child_wellbeing', name: 'Child wellbeing', pressure: 66, trend: 'worsening', headline: 'Some children are carrying strain long before adults notice.' },
  { id: 'transport_reliability', name: 'Transport reliability', pressure: 61, trend: 'steady', headline: 'Journeys that fray patience are fraying trust too.' },
  { id: 'cost_of_living_pressure', name: 'Cost of living pressure', pressure: 69, trend: 'worsening', headline: 'Ordinary decency is getting more expensive.' },
  { id: 'youth_belonging', name: 'Youth belonging', pressure: 58, trend: 'steady', headline: 'Idle afternoons are turning into brittle moods.' },
  { id: 'energy_affordability', name: 'Energy affordability', pressure: 54, trend: 'steady', headline: 'Cold spells and price shocks could travel quickly through the country.' },
  { id: 'trust_in_public_life', name: 'Trust in public life', pressure: 52, trend: 'steady', headline: 'Trust is present, but it is asking to be deserved.' },
];

export function createInitialWorldState(): WorldState {
  return {
    country: JSON.parse(JSON.stringify(initialCountryState)),
    regions: JSON.parse(JSON.stringify(initialRegions)),
    institutions: JSON.parse(JSON.stringify(initialInstitutions)),
    issues: JSON.parse(JSON.stringify(initialIssues)),
    scenarios: [],
    selectedRegionId: 'riverglass',
  };
}
